x_offset = argument0;y_offset = argument1;
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 512+ x_offset;
lastcreated.cell_y = 544+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 352+ x_offset;
lastcreated.cell_y = 496+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 384+ x_offset;
lastcreated.cell_y = 512+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 416+ x_offset;
lastcreated.cell_y = 528+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 448+ x_offset;
lastcreated.cell_y = 544+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 480+ x_offset;
lastcreated.cell_y = 560+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 320+ x_offset;
lastcreated.cell_y = 512+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 352+ x_offset;
lastcreated.cell_y = 528+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 384+ x_offset;
lastcreated.cell_y = 544+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 416+ x_offset;
lastcreated.cell_y = 560+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 448+ x_offset;
lastcreated.cell_y = 576+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 704+ x_offset;
lastcreated.cell_y = 224+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 736+ x_offset;
lastcreated.cell_y = 240+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 768+ x_offset;
lastcreated.cell_y = 256+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 672+ x_offset;
lastcreated.cell_y = 240+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 704+ x_offset;
lastcreated.cell_y = 256+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 736+ x_offset;
lastcreated.cell_y = 272+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 640+ x_offset;
lastcreated.cell_y = 256+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 672+ x_offset;
lastcreated.cell_y = 272+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 704+ x_offset;
lastcreated.cell_y = 288+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 736+ x_offset;
lastcreated.cell_y = 304+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 768+ x_offset;
lastcreated.cell_y = 320+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 608+ x_offset;
lastcreated.cell_y = 272+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 640+ x_offset;
lastcreated.cell_y = 288+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 672+ x_offset;
lastcreated.cell_y = 304+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 704+ x_offset;
lastcreated.cell_y = 320+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 736+ x_offset;
lastcreated.cell_y = 336+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 576+ x_offset;
lastcreated.cell_y = 288+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 608+ x_offset;
lastcreated.cell_y = 304+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 640+ x_offset;
lastcreated.cell_y = 320+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 672+ x_offset;
lastcreated.cell_y = 336+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 704+ x_offset;
lastcreated.cell_y = 352+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 896+ x_offset;
lastcreated.cell_y = 224+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 928+ x_offset;
lastcreated.cell_y = 240+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 960+ x_offset;
lastcreated.cell_y = 256+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 992+ x_offset;
lastcreated.cell_y = 272+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1024+ x_offset;
lastcreated.cell_y = 288+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 864+ x_offset;
lastcreated.cell_y = 240+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 896+ x_offset;
lastcreated.cell_y = 256+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 928+ x_offset;
lastcreated.cell_y = 272+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 960+ x_offset;
lastcreated.cell_y = 288+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 992+ x_offset;
lastcreated.cell_y = 304+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 832+ x_offset;
lastcreated.cell_y = 256+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 864+ x_offset;
lastcreated.cell_y = 272+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 896+ x_offset;
lastcreated.cell_y = 288+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 928+ x_offset;
lastcreated.cell_y = 304+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 960+ x_offset;
lastcreated.cell_y = 320+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 800+ x_offset;
lastcreated.cell_y = 272+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 832+ x_offset;
lastcreated.cell_y = 288+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 864+ x_offset;
lastcreated.cell_y = 304+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 896+ x_offset;
lastcreated.cell_y = 320+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 928+ x_offset;
lastcreated.cell_y = 336+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 768+ x_offset;
lastcreated.cell_y = 288+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 800+ x_offset;
lastcreated.cell_y = 304+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 832+ x_offset;
lastcreated.cell_y = 320+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 864+ x_offset;
lastcreated.cell_y = 336+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 896+ x_offset;
lastcreated.cell_y = 352+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 768+ x_offset;
lastcreated.cell_y = 0+ y_offset;
lastcreated.cell_z = 64;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 736+ x_offset;
lastcreated.cell_y = -16+ y_offset;
lastcreated.cell_z = 64;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 672+ x_offset;
lastcreated.cell_y = -16+ y_offset;
lastcreated.cell_z = 64;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1216+ x_offset;
lastcreated.cell_y = 64+ y_offset;
lastcreated.cell_z = 64;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1184+ x_offset;
lastcreated.cell_y = -16+ y_offset;
lastcreated.cell_z = 64;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1120+ x_offset;
lastcreated.cell_y = -16+ y_offset;
lastcreated.cell_z = 64;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1152+ x_offset;
lastcreated.cell_y = 0+ y_offset;
lastcreated.cell_z = 64;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1056+ x_offset;
lastcreated.cell_y = -16+ y_offset;
lastcreated.cell_z = 64;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1088+ x_offset;
lastcreated.cell_y = 0+ y_offset;
lastcreated.cell_z = 64;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1024+ x_offset;
lastcreated.cell_y = 0+ y_offset;
lastcreated.cell_z = 64;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1504+ x_offset;
lastcreated.cell_y = -16+ y_offset;
lastcreated.cell_z = 64;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1536+ x_offset;
lastcreated.cell_y = 0+ y_offset;
lastcreated.cell_z = 64;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1440+ x_offset;
lastcreated.cell_y = -16+ y_offset;
lastcreated.cell_z = 64;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1120+ x_offset;
lastcreated.cell_y = 560+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1088+ x_offset;
lastcreated.cell_y = 576+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1056+ x_offset;
lastcreated.cell_y = 592+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 960+ x_offset;
lastcreated.cell_y = 544+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 992+ x_offset;
lastcreated.cell_y = 560+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1024+ x_offset;
lastcreated.cell_y = 576+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1056+ x_offset;
lastcreated.cell_y = 560+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1088+ x_offset;
lastcreated.cell_y = 544+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1120+ x_offset;
lastcreated.cell_y = 528+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1152+ x_offset;
lastcreated.cell_y = 512+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1152+ x_offset;
lastcreated.cell_y = 480+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1184+ x_offset;
lastcreated.cell_y = 496+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1152+ x_offset;
lastcreated.cell_y = 448+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1184+ x_offset;
lastcreated.cell_y = 464+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1216+ x_offset;
lastcreated.cell_y = 480+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1248+ x_offset;
lastcreated.cell_y = 400+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1216+ x_offset;
lastcreated.cell_y = 416+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1184+ x_offset;
lastcreated.cell_y = 432+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1280+ x_offset;
lastcreated.cell_y = 416+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1248+ x_offset;
lastcreated.cell_y = 432+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1216+ x_offset;
lastcreated.cell_y = 448+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1440+ x_offset;
lastcreated.cell_y = 496+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1280+ x_offset;
lastcreated.cell_y = 512+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1408+ x_offset;
lastcreated.cell_y = 512+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1440+ x_offset;
lastcreated.cell_y = 528+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1312+ x_offset;
lastcreated.cell_y = 528+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1376+ x_offset;
lastcreated.cell_y = 528+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1408+ x_offset;
lastcreated.cell_y = 544+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1440+ x_offset;
lastcreated.cell_y = 560+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1344+ x_offset;
lastcreated.cell_y = 544+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1312+ x_offset;
lastcreated.cell_y = 560+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1376+ x_offset;
lastcreated.cell_y = 560+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1344+ x_offset;
lastcreated.cell_y = 576+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1312+ x_offset;
lastcreated.cell_y = 592+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1408+ x_offset;
lastcreated.cell_y = 576+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1440+ x_offset;
lastcreated.cell_y = 592+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1472+ x_offset;
lastcreated.cell_y = 608+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1376+ x_offset;
lastcreated.cell_y = 592+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1408+ x_offset;
lastcreated.cell_y = 608+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1440+ x_offset;
lastcreated.cell_y = 624+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1344+ x_offset;
lastcreated.cell_y = 608+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1312+ x_offset;
lastcreated.cell_y = 624+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1376+ x_offset;
lastcreated.cell_y = 624+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1344+ x_offset;
lastcreated.cell_y = 640+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1312+ x_offset;
lastcreated.cell_y = 656+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1408+ x_offset;
lastcreated.cell_y = 640+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1440+ x_offset;
lastcreated.cell_y = 656+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1376+ x_offset;
lastcreated.cell_y = 656+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1408+ x_offset;
lastcreated.cell_y = 672+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1440+ x_offset;
lastcreated.cell_y = 688+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1344+ x_offset;
lastcreated.cell_y = 672+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1312+ x_offset;
lastcreated.cell_y = 688+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1376+ x_offset;
lastcreated.cell_y = 688+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1408+ x_offset;
lastcreated.cell_y = 704+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1440+ x_offset;
lastcreated.cell_y = 720+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1344+ x_offset;
lastcreated.cell_y = 704+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1376+ x_offset;
lastcreated.cell_y = 720+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1408+ x_offset;
lastcreated.cell_y = 736+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1344+ x_offset;
lastcreated.cell_y = 736+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1376+ x_offset;
lastcreated.cell_y = 752+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1408+ x_offset;
lastcreated.cell_y = 768+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1312+ x_offset;
lastcreated.cell_y = 752+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1344+ x_offset;
lastcreated.cell_y = 768+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1376+ x_offset;
lastcreated.cell_y = 784+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1408+ x_offset;
lastcreated.cell_y = 800+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1376+ x_offset;
lastcreated.cell_y = 816+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1344+ x_offset;
lastcreated.cell_y = 832+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1312+ x_offset;
lastcreated.cell_y = 848+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1312+ x_offset;
lastcreated.cell_y = 784+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1344+ x_offset;
lastcreated.cell_y = 800+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1312+ x_offset;
lastcreated.cell_y = 816+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1280+ x_offset;
lastcreated.cell_y = 832+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1248+ x_offset;
lastcreated.cell_y = 848+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1280+ x_offset;
lastcreated.cell_y = 800+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1248+ x_offset;
lastcreated.cell_y = 816+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1216+ x_offset;
lastcreated.cell_y = 832+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1120+ x_offset;
lastcreated.cell_y = 784+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1152+ x_offset;
lastcreated.cell_y = 800+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1184+ x_offset;
lastcreated.cell_y = 816+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1280+ x_offset;
lastcreated.cell_y = 768+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1248+ x_offset;
lastcreated.cell_y = 784+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1152+ x_offset;
lastcreated.cell_y = 768+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1184+ x_offset;
lastcreated.cell_y = 784+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1216+ x_offset;
lastcreated.cell_y = 800+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1152+ x_offset;
lastcreated.cell_y = 736+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1184+ x_offset;
lastcreated.cell_y = 752+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1216+ x_offset;
lastcreated.cell_y = 768+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1248+ x_offset;
lastcreated.cell_y = 688+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1280+ x_offset;
lastcreated.cell_y = 704+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1312+ x_offset;
lastcreated.cell_y = 720+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1216+ x_offset;
lastcreated.cell_y = 704+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1248+ x_offset;
lastcreated.cell_y = 720+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1280+ x_offset;
lastcreated.cell_y = 736+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1184+ x_offset;
lastcreated.cell_y = 720+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1216+ x_offset;
lastcreated.cell_y = 736+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1248+ x_offset;
lastcreated.cell_y = 752+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1056+ x_offset;
lastcreated.cell_y = 784+ y_offset;
lastcreated.cell_z = 64;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1024+ x_offset;
lastcreated.cell_y = 800+ y_offset;
lastcreated.cell_z = 64;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 992+ x_offset;
lastcreated.cell_y = 816+ y_offset;
lastcreated.cell_z = 64;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1024+ x_offset;
lastcreated.cell_y = 832+ y_offset;
lastcreated.cell_z = 64;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 992+ x_offset;
lastcreated.cell_y = 848+ y_offset;
lastcreated.cell_z = 64;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1024+ x_offset;
lastcreated.cell_y = 864+ y_offset;
lastcreated.cell_z = 64;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1056+ x_offset;
lastcreated.cell_y = 880+ y_offset;
lastcreated.cell_z = 64;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1024+ x_offset;
lastcreated.cell_y = 768+ y_offset;
lastcreated.cell_z = 64;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 992+ x_offset;
lastcreated.cell_y = 784+ y_offset;
lastcreated.cell_z = 64;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1440+ x_offset;
lastcreated.cell_y = 1168+ y_offset;
lastcreated.cell_z = 128;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1568+ x_offset;
lastcreated.cell_y = 1136+ y_offset;
lastcreated.cell_z = 128;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1472+ x_offset;
lastcreated.cell_y = 1568+ y_offset;
lastcreated.cell_z = 128;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1600+ x_offset;
lastcreated.cell_y = 1184+ y_offset;
lastcreated.cell_z = 128;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1568+ x_offset;
lastcreated.cell_y = 1168+ y_offset;
lastcreated.cell_z = 128;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1568+ x_offset;
lastcreated.cell_y = 1488+ y_offset;
lastcreated.cell_z = 128;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1568+ x_offset;
lastcreated.cell_y = 1520+ y_offset;
lastcreated.cell_z = 128;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1536+ x_offset;
lastcreated.cell_y = 1536+ y_offset;
lastcreated.cell_z = 128;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1568+ x_offset;
lastcreated.cell_y = 1552+ y_offset;
lastcreated.cell_z = 128;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1504+ x_offset;
lastcreated.cell_y = 1552+ y_offset;
lastcreated.cell_z = 128;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1536+ x_offset;
lastcreated.cell_y = 1568+ y_offset;
lastcreated.cell_z = 128;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1568+ x_offset;
lastcreated.cell_y = 1584+ y_offset;
lastcreated.cell_z = 128;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1568+ x_offset;
lastcreated.cell_y = 1616+ y_offset;
lastcreated.cell_z = 128;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1504+ x_offset;
lastcreated.cell_y = 1584+ y_offset;
lastcreated.cell_z = 128;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1536+ x_offset;
lastcreated.cell_y = 1600+ y_offset;
lastcreated.cell_z = 128;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1504+ x_offset;
lastcreated.cell_y = 1616+ y_offset;
lastcreated.cell_z = 128;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1472+ x_offset;
lastcreated.cell_y = 1600+ y_offset;
lastcreated.cell_z = 128;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1440+ x_offset;
lastcreated.cell_y = 1616+ y_offset;
lastcreated.cell_z = 128;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1440+ x_offset;
lastcreated.cell_y = 1584+ y_offset;
lastcreated.cell_z = 128;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1408+ x_offset;
lastcreated.cell_y = 1600+ y_offset;
lastcreated.cell_z = 128;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1280+ x_offset;
lastcreated.cell_y = 1600+ y_offset;
lastcreated.cell_z = 128;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1280+ x_offset;
lastcreated.cell_y = 1568+ y_offset;
lastcreated.cell_z = 128;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1248+ x_offset;
lastcreated.cell_y = 1584+ y_offset;
lastcreated.cell_z = 128;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1216+ x_offset;
lastcreated.cell_y = 1600+ y_offset;
lastcreated.cell_z = 128;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1216+ x_offset;
lastcreated.cell_y = 1568+ y_offset;
lastcreated.cell_z = 128;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
