x_offset = argument0;y_offset = argument1;
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1312+ x_offset;
lastcreated.cell_y = 848+ y_offset;
lastcreated.cell_z = 128;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1280+ x_offset;
lastcreated.cell_y = 864+ y_offset;
lastcreated.cell_z = 128;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1248+ x_offset;
lastcreated.cell_y = 880+ y_offset;
lastcreated.cell_z = 128;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1344+ x_offset;
lastcreated.cell_y = 864+ y_offset;
lastcreated.cell_z = 128;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1376+ x_offset;
lastcreated.cell_y = 880+ y_offset;
lastcreated.cell_z = 128;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1408+ x_offset;
lastcreated.cell_y = 896+ y_offset;
lastcreated.cell_z = 128;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1440+ x_offset;
lastcreated.cell_y = 912+ y_offset;
lastcreated.cell_z = 128;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1312+ x_offset;
lastcreated.cell_y = 880+ y_offset;
lastcreated.cell_z = 128;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1344+ x_offset;
lastcreated.cell_y = 896+ y_offset;
lastcreated.cell_z = 128;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1376+ x_offset;
lastcreated.cell_y = 912+ y_offset;
lastcreated.cell_z = 128;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1408+ x_offset;
lastcreated.cell_y = 928+ y_offset;
lastcreated.cell_z = 128;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1280+ x_offset;
lastcreated.cell_y = 896+ y_offset;
lastcreated.cell_z = 128;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1248+ x_offset;
lastcreated.cell_y = 912+ y_offset;
lastcreated.cell_z = 128;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1216+ x_offset;
lastcreated.cell_y = 928+ y_offset;
lastcreated.cell_z = 128;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1312+ x_offset;
lastcreated.cell_y = 912+ y_offset;
lastcreated.cell_z = 128;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1280+ x_offset;
lastcreated.cell_y = 928+ y_offset;
lastcreated.cell_z = 128;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1248+ x_offset;
lastcreated.cell_y = 944+ y_offset;
lastcreated.cell_z = 128;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1216+ x_offset;
lastcreated.cell_y = 960+ y_offset;
lastcreated.cell_z = 128;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1344+ x_offset;
lastcreated.cell_y = 928+ y_offset;
lastcreated.cell_z = 128;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1376+ x_offset;
lastcreated.cell_y = 944+ y_offset;
lastcreated.cell_z = 128;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1312+ x_offset;
lastcreated.cell_y = 944+ y_offset;
lastcreated.cell_z = 128;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1280+ x_offset;
lastcreated.cell_y = 960+ y_offset;
lastcreated.cell_z = 128;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1248+ x_offset;
lastcreated.cell_y = 976+ y_offset;
lastcreated.cell_z = 128;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1216+ x_offset;
lastcreated.cell_y = 992+ y_offset;
lastcreated.cell_z = 128;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1312+ x_offset;
lastcreated.cell_y = 16+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1280+ x_offset;
lastcreated.cell_y = 32+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1248+ x_offset;
lastcreated.cell_y = 48+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1216+ x_offset;
lastcreated.cell_y = 64+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1344+ x_offset;
lastcreated.cell_y = 32+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1312+ x_offset;
lastcreated.cell_y = 48+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1280+ x_offset;
lastcreated.cell_y = 64+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1248+ x_offset;
lastcreated.cell_y = 80+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1376+ x_offset;
lastcreated.cell_y = 48+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1344+ x_offset;
lastcreated.cell_y = 64+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1312+ x_offset;
lastcreated.cell_y = 80+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1280+ x_offset;
lastcreated.cell_y = 96+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1408+ x_offset;
lastcreated.cell_y = 64+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1376+ x_offset;
lastcreated.cell_y = 80+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1344+ x_offset;
lastcreated.cell_y = 96+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1312+ x_offset;
lastcreated.cell_y = 112+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1440+ x_offset;
lastcreated.cell_y = 80+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1472+ x_offset;
lastcreated.cell_y = 96+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1504+ x_offset;
lastcreated.cell_y = 112+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1536+ x_offset;
lastcreated.cell_y = 128+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1408+ x_offset;
lastcreated.cell_y = 96+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1376+ x_offset;
lastcreated.cell_y = 112+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1344+ x_offset;
lastcreated.cell_y = 128+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1440+ x_offset;
lastcreated.cell_y = 112+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1408+ x_offset;
lastcreated.cell_y = 128+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1376+ x_offset;
lastcreated.cell_y = 144+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1344+ x_offset;
lastcreated.cell_y = 160+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1472+ x_offset;
lastcreated.cell_y = 128+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1504+ x_offset;
lastcreated.cell_y = 144+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1536+ x_offset;
lastcreated.cell_y = 160+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1568+ x_offset;
lastcreated.cell_y = 176+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1440+ x_offset;
lastcreated.cell_y = 144+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1408+ x_offset;
lastcreated.cell_y = 160+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1376+ x_offset;
lastcreated.cell_y = 176+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1472+ x_offset;
lastcreated.cell_y = 160+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1504+ x_offset;
lastcreated.cell_y = 176+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1536+ x_offset;
lastcreated.cell_y = 192+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1568+ x_offset;
lastcreated.cell_y = 208+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1440+ x_offset;
lastcreated.cell_y = 176+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1472+ x_offset;
lastcreated.cell_y = 192+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1504+ x_offset;
lastcreated.cell_y = 208+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1536+ x_offset;
lastcreated.cell_y = 224+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1408+ x_offset;
lastcreated.cell_y = 192+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1440+ x_offset;
lastcreated.cell_y = 208+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1472+ x_offset;
lastcreated.cell_y = 224+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1504+ x_offset;
lastcreated.cell_y = 240+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1376+ x_offset;
lastcreated.cell_y = 208+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1408+ x_offset;
lastcreated.cell_y = 224+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1440+ x_offset;
lastcreated.cell_y = 240+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1472+ x_offset;
lastcreated.cell_y = 256+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 224+ x_offset;
lastcreated.cell_y = 48+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 256+ x_offset;
lastcreated.cell_y = 64+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 288+ x_offset;
lastcreated.cell_y = 80+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 192+ x_offset;
lastcreated.cell_y = 64+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 224+ x_offset;
lastcreated.cell_y = 80+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 256+ x_offset;
lastcreated.cell_y = 96+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 288+ x_offset;
lastcreated.cell_y = 112+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 160+ x_offset;
lastcreated.cell_y = 80+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 128+ x_offset;
lastcreated.cell_y = 96+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 96+ x_offset;
lastcreated.cell_y = 112+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 192+ x_offset;
lastcreated.cell_y = 96+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 224+ x_offset;
lastcreated.cell_y = 112+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 256+ x_offset;
lastcreated.cell_y = 128+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 288+ x_offset;
lastcreated.cell_y = 144+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 160+ x_offset;
lastcreated.cell_y = 112+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 192+ x_offset;
lastcreated.cell_y = 128+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 224+ x_offset;
lastcreated.cell_y = 144+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 256+ x_offset;
lastcreated.cell_y = 160+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 128+ x_offset;
lastcreated.cell_y = 128+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 96+ x_offset;
lastcreated.cell_y = 144+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 64+ x_offset;
lastcreated.cell_y = 160+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 160+ x_offset;
lastcreated.cell_y = 144+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 192+ x_offset;
lastcreated.cell_y = 160+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 224+ x_offset;
lastcreated.cell_y = 176+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 256+ x_offset;
lastcreated.cell_y = 192+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 128+ x_offset;
lastcreated.cell_y = 160+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 160+ x_offset;
lastcreated.cell_y = 176+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 192+ x_offset;
lastcreated.cell_y = 192+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 224+ x_offset;
lastcreated.cell_y = 208+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 96+ x_offset;
lastcreated.cell_y = 176+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 64+ x_offset;
lastcreated.cell_y = 192+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 128+ x_offset;
lastcreated.cell_y = 192+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 160+ x_offset;
lastcreated.cell_y = 208+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 192+ x_offset;
lastcreated.cell_y = 224+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 224+ x_offset;
lastcreated.cell_y = 240+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 96+ x_offset;
lastcreated.cell_y = 208+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 128+ x_offset;
lastcreated.cell_y = 224+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 160+ x_offset;
lastcreated.cell_y = 240+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 192+ x_offset;
lastcreated.cell_y = 256+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 64+ x_offset;
lastcreated.cell_y = 224+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 96+ x_offset;
lastcreated.cell_y = 240+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 128+ x_offset;
lastcreated.cell_y = 256+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 160+ x_offset;
lastcreated.cell_y = 272+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 32+ x_offset;
lastcreated.cell_y = 240+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 64+ x_offset;
lastcreated.cell_y = 256+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 96+ x_offset;
lastcreated.cell_y = 272+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 128+ x_offset;
lastcreated.cell_y = 288+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0+ x_offset;
lastcreated.cell_y = 256+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 272+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 32+ x_offset;
lastcreated.cell_y = 272+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0+ x_offset;
lastcreated.cell_y = 288+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 304+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 64+ x_offset;
lastcreated.cell_y = 288+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 96+ x_offset;
lastcreated.cell_y = 304+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 128+ x_offset;
lastcreated.cell_y = 320+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 160+ x_offset;
lastcreated.cell_y = 336+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 32+ x_offset;
lastcreated.cell_y = 304+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 64+ x_offset;
lastcreated.cell_y = 320+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 96+ x_offset;
lastcreated.cell_y = 336+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 128+ x_offset;
lastcreated.cell_y = 352+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0+ x_offset;
lastcreated.cell_y = 320+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 32+ x_offset;
lastcreated.cell_y = 336+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 64+ x_offset;
lastcreated.cell_y = 352+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 96+ x_offset;
lastcreated.cell_y = 368+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 336+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0+ x_offset;
lastcreated.cell_y = 352+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 32+ x_offset;
lastcreated.cell_y = 368+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 64+ x_offset;
lastcreated.cell_y = 384+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 368+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0+ x_offset;
lastcreated.cell_y = 384+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 32+ x_offset;
lastcreated.cell_y = 400+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 1424+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 1456+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 224+ x_offset;
lastcreated.cell_y = 1456+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 256+ x_offset;
lastcreated.cell_y = 1472+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 192+ x_offset;
lastcreated.cell_y = 1536+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 224+ x_offset;
lastcreated.cell_y = 1552+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 320+ x_offset;
lastcreated.cell_y = 1472+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 288+ x_offset;
lastcreated.cell_y = 1488+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 256+ x_offset;
lastcreated.cell_y = 1504+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 224+ x_offset;
lastcreated.cell_y = 1520+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 352+ x_offset;
lastcreated.cell_y = 1488+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 320+ x_offset;
lastcreated.cell_y = 1504+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 288+ x_offset;
lastcreated.cell_y = 1520+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 256+ x_offset;
lastcreated.cell_y = 1536+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 384+ x_offset;
lastcreated.cell_y = 1504+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 352+ x_offset;
lastcreated.cell_y = 1520+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 320+ x_offset;
lastcreated.cell_y = 1536+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 288+ x_offset;
lastcreated.cell_y = 1552+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 416+ x_offset;
lastcreated.cell_y = 1520+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 384+ x_offset;
lastcreated.cell_y = 1536+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 352+ x_offset;
lastcreated.cell_y = 1552+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 320+ x_offset;
lastcreated.cell_y = 1568+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 448+ x_offset;
lastcreated.cell_y = 1536+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 416+ x_offset;
lastcreated.cell_y = 1552+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 384+ x_offset;
lastcreated.cell_y = 1568+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 352+ x_offset;
lastcreated.cell_y = 1584+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 384+ x_offset;
lastcreated.cell_y = 1600+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 416+ x_offset;
lastcreated.cell_y = 1616+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 512+ x_offset;
lastcreated.cell_y = 1536+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 480+ x_offset;
lastcreated.cell_y = 1552+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 448+ x_offset;
lastcreated.cell_y = 1568+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 416+ x_offset;
lastcreated.cell_y = 1584+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 544+ x_offset;
lastcreated.cell_y = 1552+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 576+ x_offset;
lastcreated.cell_y = 1568+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 608+ x_offset;
lastcreated.cell_y = 1584+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 640+ x_offset;
lastcreated.cell_y = 1600+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 512+ x_offset;
lastcreated.cell_y = 1568+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 544+ x_offset;
lastcreated.cell_y = 1584+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 576+ x_offset;
lastcreated.cell_y = 1600+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 608+ x_offset;
lastcreated.cell_y = 1616+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 480+ x_offset;
lastcreated.cell_y = 1584+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 512+ x_offset;
lastcreated.cell_y = 1600+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 544+ x_offset;
lastcreated.cell_y = 1616+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 448+ x_offset;
lastcreated.cell_y = 1600+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 480+ x_offset;
lastcreated.cell_y = 1616+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1536+ x_offset;
lastcreated.cell_y = 1376+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1568+ x_offset;
lastcreated.cell_y = 1392+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1600+ x_offset;
lastcreated.cell_y = 1408+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1504+ x_offset;
lastcreated.cell_y = 1392+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1472+ x_offset;
lastcreated.cell_y = 1408+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1440+ x_offset;
lastcreated.cell_y = 1424+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1536+ x_offset;
lastcreated.cell_y = 1408+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1568+ x_offset;
lastcreated.cell_y = 1424+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1600+ x_offset;
lastcreated.cell_y = 1440+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1504+ x_offset;
lastcreated.cell_y = 1424+ y_offset;
lastcreated.cell_z = 192;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
