x_offset = argument0;y_offset = argument1;
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1376+ x_offset;
lastcreated.cell_y = 496+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1248+ x_offset;
lastcreated.cell_y = 464+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1280+ x_offset;
lastcreated.cell_y = 480+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1312+ x_offset;
lastcreated.cell_y = 496+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1344+ x_offset;
lastcreated.cell_y = 512+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 704+ x_offset;
lastcreated.cell_y = 1152+ y_offset;
lastcreated.cell_z = 64;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 736+ x_offset;
lastcreated.cell_y = 1168+ y_offset;
lastcreated.cell_z = 64;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 768+ x_offset;
lastcreated.cell_y = 1152+ y_offset;
lastcreated.cell_z = 64;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 704+ x_offset;
lastcreated.cell_y = 1120+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 768+ x_offset;
lastcreated.cell_y = 1120+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 768+ x_offset;
lastcreated.cell_y = 1056+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 800+ x_offset;
lastcreated.cell_y = 1072+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 704+ x_offset;
lastcreated.cell_y = 1056+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 736+ x_offset;
lastcreated.cell_y = 1072+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 768+ x_offset;
lastcreated.cell_y = 1088+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 672+ x_offset;
lastcreated.cell_y = 1072+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 704+ x_offset;
lastcreated.cell_y = 1088+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 736+ x_offset;
lastcreated.cell_y = 1104+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 320+ x_offset;
lastcreated.cell_y = 1376+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 352+ x_offset;
lastcreated.cell_y = 1392+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 256+ x_offset;
lastcreated.cell_y = 1376+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 288+ x_offset;
lastcreated.cell_y = 1392+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 320+ x_offset;
lastcreated.cell_y = 1408+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 224+ x_offset;
lastcreated.cell_y = 1392+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 256+ x_offset;
lastcreated.cell_y = 1408+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 288+ x_offset;
lastcreated.cell_y = 1424+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1056+ x_offset;
lastcreated.cell_y = 720+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_doodad_rock_00;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 992+ x_offset;
lastcreated.cell_y = 560+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_doodad_rock_00;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 640+ x_offset;
lastcreated.cell_y = 768+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_doodad_tree_00;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 768+ x_offset;
lastcreated.cell_y = 480+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_doodad_tree_00;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1184+ x_offset;
lastcreated.cell_y = 272+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_doodad_rock_00;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1280+ x_offset;
lastcreated.cell_y = 320+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_doodad_rock_00;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 224+ x_offset;
lastcreated.cell_y = 176+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_doodad_rock_00;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 416+ x_offset;
lastcreated.cell_y = 304+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_doodad_rock_00;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 288+ x_offset;
lastcreated.cell_y = 304+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_doodad_rock_00;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 64+ x_offset;
lastcreated.cell_y = 736+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_doodad_rock_00;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 160+ x_offset;
lastcreated.cell_y = 816+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_doodad_rock_00;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_npc);
lastcreated.npc_x = -384+ x_offset;
lastcreated.npc_y = 0+ y_offset;
lastcreated.npc_type = obj_enemyspawn_g_l_ex;
lastcreated.chamber = id;
ds_list_add(npc_list,lastcreated);
with(lastcreated){event_user(0);}
lastcreated = instance_create(0,0,obj_abstract_npc);
lastcreated.npc_x = -384+ x_offset;
lastcreated.npc_y = 0+ y_offset;
lastcreated.npc_type = obj_enemyspawn_g_l_ex;
lastcreated.chamber = id;
ds_list_add(npc_list,lastcreated);
with(lastcreated){event_user(0);}
lastcreated = instance_create(0,0,obj_abstract_npc);
lastcreated.npc_x = -384+ x_offset;
lastcreated.npc_y = 0+ y_offset;
lastcreated.npc_type = obj_enemyspawn_g_m_ex;
lastcreated.chamber = id;
ds_list_add(npc_list,lastcreated);
with(lastcreated){event_user(0);}
lastcreated = instance_create(0,0,obj_abstract_npc);
lastcreated.npc_x = -384+ x_offset;
lastcreated.npc_y = 0+ y_offset;
lastcreated.npc_type = obj_enemyspawn_g_m_ex;
lastcreated.chamber = id;
ds_list_add(npc_list,lastcreated);
with(lastcreated){event_user(0);}
