x_offset = argument0;y_offset = argument1;
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 96+ x_offset;
lastcreated.cell_y = 304+ y_offset;
lastcreated.cell_z = 64;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 256+ x_offset;
lastcreated.cell_y = 288+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 288+ x_offset;
lastcreated.cell_y = 304+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 192+ x_offset;
lastcreated.cell_y = 288+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 224+ x_offset;
lastcreated.cell_y = 304+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 256+ x_offset;
lastcreated.cell_y = 320+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 160+ x_offset;
lastcreated.cell_y = 304+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 192+ x_offset;
lastcreated.cell_y = 320+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 224+ x_offset;
lastcreated.cell_y = 336+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 128+ x_offset;
lastcreated.cell_y = 320+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 160+ x_offset;
lastcreated.cell_y = 336+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 192+ x_offset;
lastcreated.cell_y = 352+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 96+ x_offset;
lastcreated.cell_y = 976+ y_offset;
lastcreated.cell_z = 64;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 128+ x_offset;
lastcreated.cell_y = 992+ y_offset;
lastcreated.cell_z = 64;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 160+ x_offset;
lastcreated.cell_y = 976+ y_offset;
lastcreated.cell_z = 64;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 96+ x_offset;
lastcreated.cell_y = 944+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 160+ x_offset;
lastcreated.cell_y = 944+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 160+ x_offset;
lastcreated.cell_y = 880+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 192+ x_offset;
lastcreated.cell_y = 896+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 96+ x_offset;
lastcreated.cell_y = 880+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 128+ x_offset;
lastcreated.cell_y = 896+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 160+ x_offset;
lastcreated.cell_y = 912+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 64+ x_offset;
lastcreated.cell_y = 896+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 96+ x_offset;
lastcreated.cell_y = 912+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 128+ x_offset;
lastcreated.cell_y = 928+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 640+ x_offset;
lastcreated.cell_y = 608+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 672+ x_offset;
lastcreated.cell_y = 624+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 576+ x_offset;
lastcreated.cell_y = 608+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 608+ x_offset;
lastcreated.cell_y = 624+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 640+ x_offset;
lastcreated.cell_y = 640+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 544+ x_offset;
lastcreated.cell_y = 624+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 576+ x_offset;
lastcreated.cell_y = 640+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 608+ x_offset;
lastcreated.cell_y = 656+ y_offset;
lastcreated.cell_z = 0;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_npc);
lastcreated.npc_x = -384+ x_offset;
lastcreated.npc_y = 0+ y_offset;
lastcreated.npc_type = obj_enemyspawn_g_l_ex;
lastcreated.chamber = id;
ds_list_add(npc_list,lastcreated);
with(lastcreated){event_user(0);}
lastcreated = instance_create(0,0,obj_abstract_npc);
lastcreated.npc_x = -384+ x_offset;
lastcreated.npc_y = 0+ y_offset;
lastcreated.npc_type = obj_enemyspawn_g_l_ex;
lastcreated.chamber = id;
ds_list_add(npc_list,lastcreated);
with(lastcreated){event_user(0);}
lastcreated = instance_create(0,0,obj_abstract_npc);
lastcreated.npc_x = -384+ x_offset;
lastcreated.npc_y = 0+ y_offset;
lastcreated.npc_type = obj_enemyspawn_g_l_ex;
lastcreated.chamber = id;
ds_list_add(npc_list,lastcreated);
with(lastcreated){event_user(0);}
lastcreated = instance_create(0,0,obj_abstract_npc);
lastcreated.npc_x = -384+ x_offset;
lastcreated.npc_y = 0+ y_offset;
lastcreated.npc_type = obj_enemyspawn_g_l_ex;
lastcreated.chamber = id;
ds_list_add(npc_list,lastcreated);
with(lastcreated){event_user(0);}
lastcreated = instance_create(0,0,obj_abstract_npc);
lastcreated.npc_x = -384+ x_offset;
lastcreated.npc_y = 0+ y_offset;
lastcreated.npc_type = obj_enemyspawn_g_l_ex;
lastcreated.chamber = id;
ds_list_add(npc_list,lastcreated);
with(lastcreated){event_user(0);}
lastcreated = instance_create(0,0,obj_abstract_npc);
lastcreated.npc_x = -384+ x_offset;
lastcreated.npc_y = 0+ y_offset;
lastcreated.npc_type = obj_enemyspawn_g_m_ex;
lastcreated.chamber = id;
ds_list_add(npc_list,lastcreated);
with(lastcreated){event_user(0);}
lastcreated = instance_create(0,0,obj_abstract_npc);
lastcreated.npc_x = -384+ x_offset;
lastcreated.npc_y = 0+ y_offset;
lastcreated.npc_type = obj_enemyspawn_g_m_ex;
lastcreated.chamber = id;
ds_list_add(npc_list,lastcreated);
with(lastcreated){event_user(0);}
lastcreated = instance_create(0,0,obj_abstract_npc);
lastcreated.npc_x = -384+ x_offset;
lastcreated.npc_y = 0+ y_offset;
lastcreated.npc_type = obj_enemyspawn_g_m_ex;
lastcreated.chamber = id;
ds_list_add(npc_list,lastcreated);
with(lastcreated){event_user(0);}
lastcreated = instance_create(0,0,obj_abstract_npc);
lastcreated.npc_x = -384+ x_offset;
lastcreated.npc_y = 0+ y_offset;
lastcreated.npc_type = obj_enemyspawn_g_m_ex;
lastcreated.chamber = id;
ds_list_add(npc_list,lastcreated);
with(lastcreated){event_user(0);}
lastcreated = instance_create(0,0,obj_abstract_npc);
lastcreated.npc_x = -384+ x_offset;
lastcreated.npc_y = 0+ y_offset;
lastcreated.npc_type = obj_enemyspawn_g_m_ex;
lastcreated.chamber = id;
ds_list_add(npc_list,lastcreated);
with(lastcreated){event_user(0);}
lastcreated = instance_create(0,0,obj_abstract_npc);
lastcreated.npc_x = -384+ x_offset;
lastcreated.npc_y = 0+ y_offset;
lastcreated.npc_type = obj_enemyspawn_g_m_ex;
lastcreated.chamber = id;
ds_list_add(npc_list,lastcreated);
with(lastcreated){event_user(0);}
lastcreated = instance_create(0,0,obj_abstract_npc);
lastcreated.npc_x = -384+ x_offset;
lastcreated.npc_y = 0+ y_offset;
lastcreated.npc_type = obj_enemyspawn_g_m_ex;
lastcreated.chamber = id;
ds_list_add(npc_list,lastcreated);
with(lastcreated){event_user(0);}
lastcreated = instance_create(0,0,obj_abstract_npc);
lastcreated.npc_x = -384+ x_offset;
lastcreated.npc_y = 0+ y_offset;
lastcreated.npc_type = obj_enemyspawn_g_m_ex;
lastcreated.chamber = id;
ds_list_add(npc_list,lastcreated);
with(lastcreated){event_user(0);}
