x_offset = argument0;y_offset = argument1;
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 1456+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0+ x_offset;
lastcreated.cell_y = 1472+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 32+ x_offset;
lastcreated.cell_y = 1488+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 64+ x_offset;
lastcreated.cell_y = 1504+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 1488+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0+ x_offset;
lastcreated.cell_y = 1504+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 32+ x_offset;
lastcreated.cell_y = 1520+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 1520+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0+ x_offset;
lastcreated.cell_y = 1536+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 1552+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 1296+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0+ x_offset;
lastcreated.cell_y = 1312+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 1328+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0+ x_offset;
lastcreated.cell_y = 1344+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 1360+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0+ x_offset;
lastcreated.cell_y = 1376+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 1392+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0+ x_offset;
lastcreated.cell_y = 1408+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 1264+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0+ x_offset;
lastcreated.cell_y = 1280+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 752+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 720+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0+ x_offset;
lastcreated.cell_y = 736+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 496+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 688+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0+ x_offset;
lastcreated.cell_y = 704+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 944+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0+ x_offset;
lastcreated.cell_y = 960+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 32+ x_offset;
lastcreated.cell_y = 976+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 976+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0+ x_offset;
lastcreated.cell_y = 992+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 1008+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 1168+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0+ x_offset;
lastcreated.cell_y = 1184+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 1200+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0+ x_offset;
lastcreated.cell_y = 1216+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 1232+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0+ x_offset;
lastcreated.cell_y = 1248+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0+ x_offset;
lastcreated.cell_y = 1024+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 32+ x_offset;
lastcreated.cell_y = 1040+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 1040+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0+ x_offset;
lastcreated.cell_y = 1056+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 32+ x_offset;
lastcreated.cell_y = 1072+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 1072+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0+ x_offset;
lastcreated.cell_y = 1088+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 1104+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0+ x_offset;
lastcreated.cell_y = 1120+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 32+ x_offset;
lastcreated.cell_y = 1136+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 1136+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0+ x_offset;
lastcreated.cell_y = 1152+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 32+ x_offset;
lastcreated.cell_y = 1168+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0+ x_offset;
lastcreated.cell_y = 768+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 784+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 816+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 848+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 880+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0+ x_offset;
lastcreated.cell_y = 896+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 912+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0+ x_offset;
lastcreated.cell_y = 512+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 528+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0+ x_offset;
lastcreated.cell_y = 544+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 560+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0+ x_offset;
lastcreated.cell_y = 576+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 592+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0+ x_offset;
lastcreated.cell_y = 608+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 624+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0+ x_offset;
lastcreated.cell_y = 640+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 656+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 32+ x_offset;
lastcreated.cell_y = 400+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0+ x_offset;
lastcreated.cell_y = 416+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 32+ x_offset;
lastcreated.cell_y = 432+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 432+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0+ x_offset;
lastcreated.cell_y = 448+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 32+ x_offset;
lastcreated.cell_y = 464+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 464+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0+ x_offset;
lastcreated.cell_y = 480+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 32+ x_offset;
lastcreated.cell_y = 336+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0+ x_offset;
lastcreated.cell_y = 352+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 32+ x_offset;
lastcreated.cell_y = 368+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 368+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0+ x_offset;
lastcreated.cell_y = 384+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 400+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 64+ x_offset;
lastcreated.cell_y = 288+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 32+ x_offset;
lastcreated.cell_y = 304+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 304+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0+ x_offset;
lastcreated.cell_y = 320+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 336+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 32+ x_offset;
lastcreated.cell_y = 240+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 240+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0+ x_offset;
lastcreated.cell_y = 256+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 32+ x_offset;
lastcreated.cell_y = 272+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 272+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0+ x_offset;
lastcreated.cell_y = 288+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 64+ x_offset;
lastcreated.cell_y = 160+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 32+ x_offset;
lastcreated.cell_y = 176+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 64+ x_offset;
lastcreated.cell_y = 192+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 176+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0+ x_offset;
lastcreated.cell_y = 192+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 32+ x_offset;
lastcreated.cell_y = 208+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 208+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0+ x_offset;
lastcreated.cell_y = 224+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 32+ x_offset;
lastcreated.cell_y = 144+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 144+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0+ x_offset;
lastcreated.cell_y = 160+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 112+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0+ x_offset;
lastcreated.cell_y = 128+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 32+ x_offset;
lastcreated.cell_y = -16+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = -16+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0+ x_offset;
lastcreated.cell_y = 0+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 16+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 96+ x_offset;
lastcreated.cell_y = -16+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 128+ x_offset;
lastcreated.cell_y = 0+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 64+ x_offset;
lastcreated.cell_y = 0+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 96+ x_offset;
lastcreated.cell_y = 16+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 32+ x_offset;
lastcreated.cell_y = 16+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 64+ x_offset;
lastcreated.cell_y = 32+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0+ x_offset;
lastcreated.cell_y = 32+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 32+ x_offset;
lastcreated.cell_y = 48+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 48+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0+ x_offset;
lastcreated.cell_y = 64+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32+ x_offset;
lastcreated.cell_y = 80+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 160+ x_offset;
lastcreated.cell_y = 16+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 128+ x_offset;
lastcreated.cell_y = 32+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 96+ x_offset;
lastcreated.cell_y = 48+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 64+ x_offset;
lastcreated.cell_y = 64+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 32+ x_offset;
lastcreated.cell_y = 80+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0+ x_offset;
lastcreated.cell_y = 96+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 192+ x_offset;
lastcreated.cell_y = 32+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 160+ x_offset;
lastcreated.cell_y = 48+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 128+ x_offset;
lastcreated.cell_y = 64+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 96+ x_offset;
lastcreated.cell_y = 80+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 64+ x_offset;
lastcreated.cell_y = 96+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 32+ x_offset;
lastcreated.cell_y = 112+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 224+ x_offset;
lastcreated.cell_y = 48+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 192+ x_offset;
lastcreated.cell_y = 64+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 160+ x_offset;
lastcreated.cell_y = 80+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 128+ x_offset;
lastcreated.cell_y = 96+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 96+ x_offset;
lastcreated.cell_y = 112+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 64+ x_offset;
lastcreated.cell_y = 128+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 96+ x_offset;
lastcreated.cell_y = 144+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 288+ x_offset;
lastcreated.cell_y = 48+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 320+ x_offset;
lastcreated.cell_y = 64+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 256+ x_offset;
lastcreated.cell_y = 64+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 704+ x_offset;
lastcreated.cell_y = 64+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1472+ x_offset;
lastcreated.cell_y = 192+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1504+ x_offset;
lastcreated.cell_y = 208+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1536+ x_offset;
lastcreated.cell_y = 224+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1568+ x_offset;
lastcreated.cell_y = 240+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1504+ x_offset;
lastcreated.cell_y = 240+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1536+ x_offset;
lastcreated.cell_y = 256+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1504+ x_offset;
lastcreated.cell_y = 272+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1504+ x_offset;
lastcreated.cell_y = 304+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1536+ x_offset;
lastcreated.cell_y = 320+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1568+ x_offset;
lastcreated.cell_y = 336+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1536+ x_offset;
lastcreated.cell_y = 352+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1536+ x_offset;
lastcreated.cell_y = 416+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1568+ x_offset;
lastcreated.cell_y = 432+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1536+ x_offset;
lastcreated.cell_y = 512+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1504+ x_offset;
lastcreated.cell_y = 528+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1504+ x_offset;
lastcreated.cell_y = 592+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1536+ x_offset;
lastcreated.cell_y = 608+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1504+ x_offset;
lastcreated.cell_y = 624+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1504+ x_offset;
lastcreated.cell_y = 656+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1536+ x_offset;
lastcreated.cell_y = 672+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1504+ x_offset;
lastcreated.cell_y = 688+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1504+ x_offset;
lastcreated.cell_y = 720+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1536+ x_offset;
lastcreated.cell_y = 736+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1472+ x_offset;
lastcreated.cell_y = 736+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1504+ x_offset;
lastcreated.cell_y = 752+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1536+ x_offset;
lastcreated.cell_y = 768+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1568+ x_offset;
lastcreated.cell_y = 784+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1472+ x_offset;
lastcreated.cell_y = 768+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1504+ x_offset;
lastcreated.cell_y = 784+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1536+ x_offset;
lastcreated.cell_y = 800+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1440+ x_offset;
lastcreated.cell_y = 784+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1472+ x_offset;
lastcreated.cell_y = 800+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1504+ x_offset;
lastcreated.cell_y = 816+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1536+ x_offset;
lastcreated.cell_y = 832+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1568+ x_offset;
lastcreated.cell_y = 848+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1440+ x_offset;
lastcreated.cell_y = 816+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1472+ x_offset;
lastcreated.cell_y = 832+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1504+ x_offset;
lastcreated.cell_y = 848+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1536+ x_offset;
lastcreated.cell_y = 864+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1440+ x_offset;
lastcreated.cell_y = 848+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1472+ x_offset;
lastcreated.cell_y = 864+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1504+ x_offset;
lastcreated.cell_y = 880+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1408+ x_offset;
lastcreated.cell_y = 864+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1440+ x_offset;
lastcreated.cell_y = 880+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1472+ x_offset;
lastcreated.cell_y = 896+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1504+ x_offset;
lastcreated.cell_y = 912+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1536+ x_offset;
lastcreated.cell_y = 928+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1408+ x_offset;
lastcreated.cell_y = 896+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1440+ x_offset;
lastcreated.cell_y = 912+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1472+ x_offset;
lastcreated.cell_y = 928+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1504+ x_offset;
lastcreated.cell_y = 944+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1408+ x_offset;
lastcreated.cell_y = 928+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1440+ x_offset;
lastcreated.cell_y = 944+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1472+ x_offset;
lastcreated.cell_y = 960+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1504+ x_offset;
lastcreated.cell_y = 976+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 1536+ x_offset;
lastcreated.cell_y = 992+ y_offset;
lastcreated.cell_z = 256;
lastcreated.cell_type = obj_ground;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
